# Generated by Django 3.0.3 on 2020-08-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=255)),
                ('location_code', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('total_images', models.IntegerField(default=0)),
                ('failed_images', models.IntegerField(default=0)),
                ('batch_status', models.IntegerField(default=0)),
                ('profile', models.CharField(max_length=255)),
                ('csv_file_url', models.URLField()),
            ],
        ),
    ]
