# Generated by Django 3.0.3 on 2020-08-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_module', '0002_batch_config'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='batch',
            table='batches',
        ),
    ]
