# Generated by Django 3.0.3 on 2020-08-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_module', '0004_auto_20200820_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
