# Generated by Django 3.0.3 on 2020-08-20 19:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('batch_module', '0005_batch_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBank',
            fields=[
                ('file_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('URL', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('no_of_samples', models.IntegerField(default=0)),
                ('sample_details', models.TextField(blank=True, default={}, null=True)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('config', models.TextField(default={})),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch_module.Batch')),
            ],
        ),
    ]
