# Generated by Django 3.0.3 on 2020-08-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_module', '0006_imagebank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
